### ISSUE TITLE
was soll die Scheisse

### ISSUE THREAD

**Issue by MonsieurWe** [201lennard/Minesweeper-Console-application-in-C#1]
Das Minesweeper Logo ist Much

Der Befehl "clear" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
|   |  Ôûô  Ôûô   Ôûô  ÔûôÔûôÔûôÔûô   ÔûôÔûôÔûô  Ôûô   Ôûô  ÔûôÔûôÔûôÔûô  ÔûôÔûôÔûôÔûô  ÔûôÔûôÔûô   ÔûôÔûôÔûôÔûô  ÔûôÔûôÔûô
|| ||  Ôûô  ÔûôÔûô  Ôûô  Ôûô     Ôûô     Ôûô   Ôûô  Ôûô     Ôûô     Ôûô  Ôûô  Ôûô     Ôûô  Ôûô
| | |  Ôûô  Ôûô Ôûô Ôûô  ÔûôÔûô     ÔûôÔûô   Ôûô   Ôûô  ÔûôÔûô    ÔûôÔûô    ÔûôÔûôÔûô   ÔûôÔûô    ÔûôÔûôÔûô
|   |  Ôûô  Ôûô  ÔûôÔûô  Ôûô        Ôûô  Ôûô Ôûô Ôûô  Ôûô     Ôûô     Ôûô     Ôûô     Ôûô  Ôûô
|   |  Ôûô  Ôûô   Ôûô  ÔûôÔûôÔûôÔûô  ÔûôÔûôÔûô    Ôûô Ôûô   ÔûôÔûôÔûôÔûô  ÔûôÔûôÔûôÔûô  Ôûô     ÔûôÔûôÔûôÔûô  Ôûô  Ôûô

      MENU
ÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûáÔûá
1......Play
2......Game guide
3......Settings

**Comment by 201lennard** [comment]
BIST DU DUMM???  HAST DU ÜBERHAUPT DEN RICHTIGEN COMPILER???!!!!! BEI MIR FUNKTIONIERT ALLES

**Comment by MonsieurWe** [comment]
welchen compiler benutzt du?

**Comment by MonsieurWe** [comment]
Also Codeblock sagt Nein

**Comment by MonsieurWe** [comment]
printf("|   |  |  |   |  ||||   |||  |   |  ||||  ||||  |||   ||||  |||\n");
        printf("|| ||  |  ||  |  |     |     |   |  |     |     |  |  |     |  |\n");
        printf("| | |  |  | | |  ||     ||   |   |  ||    ||    |||   ||    |||\n");
        printf("|   |  |  |  ||  |        |  | | |  |     |     |     |     |  |\n");
        printf("|   |  |  |   |  ||||  |||    | |   ||||  ||||  |     ||||  |  |\n");

**Comment by 201lennard** [comment]
Wie gesagt vielleicht deine libraries

**Comment by 201lennard** [comment]
Und das mit den Minesweeper Logo. Das sind sonderzeichen. Kann sein dass warum auch immer Code::Blocks die nicht kennt

**Comment by MonsieurWe** [comment]
welcher Compiler

**Comment by 201lennard** [comment]
geh mal auf die Website https://www.onlinegdb.com/online_c_compiler# und mach füge das dort ein. Kann sein aber dass er an manchen stellen Fragezeichen auswirft

**Comment by MonsieurWe** [comment]
Ja doch ist schon wild

**Comment by 201lennard** [comment]
YEESSSS BRAMEIER WÄRE STOLZ
